package message

const (
	HelpForAdmins                = "help.forAdmins"
	HelpTitle                    = "help.title"
	HelpDescription              = "help.description"
	HelpForAllUsers              = "help.forAllUsers"
	HelpTribeTopODA              = "help.tribe.topoda"
	HelpTribeTopODD              = "help.tribe.topodd"
	HelpTribeTopODS              = "help.tribe.topods"
	HelpTribeTopOD               = "help.tribe.topod"
	HelpTribeTopPoints           = "help.tribe.toppoints"
	HelpAuthor                   = "help.author"
	HelpAddGroup                 = "help.addgroup"
	HelpGroups                   = "help.groups"
	HelpDeleteGroup              = "help.deletegroup"
	HelpShowEnnobledBarbs        = "help.showennobledbarbs"
	HelpObserve                  = "help.observe"
	HelpObservations             = "help.observations"
	HelpDeleteObservation        = "help.deleteobservation"
	HelpConqueredVillages        = "help.conqueredvillages"
	HelpDisableConqueredVillages = "help.disableconqueredvillages"
	HelpLostVillages             = "help.lostvillages"
	HelpDisableLostVillages      = "help.disablelostvillages"
	HelpShowInternals            = "help.showinternals"
	HelpChangageLanguage         = "help.changelanguage"
	HelpCoordsTranslation        = "help.coordstranslation"
	HelpDisableCoordsTranslation = "help.disablecoordstranslation"
)
